/**
 * Refreshes the self-hosted webfonts in /fonts and rewrites ds/tokens/fonts.css.
 *
 * The design system loads Space Grotesk, IBM Plex Sans and IBM Plex Mono from
 * the Google Fonts CDN. This site serves them itself instead — an EU company
 * page should not hand every visitor's IP to a third party for three typefaces —
 * so this script asks Google for the stylesheet, keeps the latin and latin-ext
 * faces (latin-ext is what carries ė į ų š ž č ū), downloads the woff2 files and
 * writes the @font-face rules against local paths.
 *
 * All three families are OFL; self-hosting is permitted by their licence.
 *
 *   node tools/fetch-fonts.mjs
 */
import { writeFile, mkdir, readdir, unlink } from 'node:fs/promises';
import { dirname, resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const FONT_DIR = join(ROOT, 'fonts');
const CSS_OUT = join(ROOT, 'ds', 'tokens', 'fonts.css');
const KEEP = new Set(['latin', 'latin-ext']);

// Weights are the ones tokens/typography.css can ask for: 300-700 display,
// 300/400/500/600 body plus one italic, 400/500/600 mono.
const API = 'https://fonts.googleapis.com/css2'
  + '?family=Space+Grotesk:wght@300..700'
  + '&family=IBM+Plex+Sans:ital,wght@0,300;0,400;0,500;0,600;1,400'
  + '&family=IBM+Plex+Mono:wght@400;500;600'
  + '&display=swap';
// Without a browser UA Google answers with truetype, not woff2.
const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 '
  + '(KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36';

const HEADER = `/* BlynAI Capital — webfonts.
   Space Grotesk (display), IBM Plex Sans (body), IBM Plex Mono (labels & data).

   Deviation from the shipped design system, sanctioned by its readme
   ("if the company self-hosts woff2 files, send them and this becomes real
   @font-face rules"): the files are served from /fonts instead of the Google
   Fonts CDN. An EU company page should not hand every visitor's IP to a third
   party for three typefaces, and the page keeps working without the CDN.
   Subsets: latin + latin-ext only — latin-ext is what carries ė į ų š ž č ū.
   Space Grotesk is the variable file (300-700); Plex ships static instances.

   Sources: fonts.google.com — Space Grotesk (OFL), IBM Plex Sans/Mono (OFL).
   Generated by tools/fetch-fonts.mjs — do not hand-edit. */
`;

const css = await (await fetch(API, { headers: { 'user-agent': UA } })).text();

const faces = [...css.matchAll(/\/\*\s*([a-z-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g)]
  .map(([, subset, block]) => ({
    subset,
    family: /font-family:\s*'([^']+)'/.exec(block)[1],
    style: /font-style:\s*(\S+);/.exec(block)[1],
    weight: /font-weight:\s*([^;]+);/.exec(block)[1].trim(),
    url: /url\((https:\/\/[^)]+)\)/.exec(block)[1],
    range: /unicode-range:\s*([^;]+);/.exec(block)[1].trim(),
  }))
  .filter(f => KEEP.has(f.subset))
  .map(f => ({
    ...f,
    file: `${f.family.toLowerCase().replace(/ /g, '-')}-${f.weight.replace(/ /g, '-')}`
      + `${f.style === 'italic' ? '-italic' : ''}-${f.subset}.woff2`,
  }));

if (!faces.length) throw new Error('Google returned no latin faces — check the API url.');

await mkdir(FONT_DIR, { recursive: true });
const wanted = new Set(faces.map(f => f.file));
for (const stale of await readdir(FONT_DIR)) {
  if (stale.endsWith('.woff2') && !wanted.has(stale)) await unlink(join(FONT_DIR, stale));
}
for (const file of wanted) {
  const { url } = faces.find(f => f.file === file);
  await writeFile(join(FONT_DIR, file), Buffer.from(await (await fetch(url)).arrayBuffer()));
  console.log('  fonts/' + file);
}

await writeFile(CSS_OUT, HEADER + faces.map(f =>
  `/* ${f.family} ${f.weight}${f.style === 'italic' ? ' italic' : ''} · ${f.subset} */\n`
  + `@font-face{font-family:'${f.family}';font-style:${f.style};font-weight:${f.weight};font-display:swap;\n`
  + `  src:url('../../fonts/${f.file}') format('woff2');\n`
  + `  unicode-range:${f.range}}`
).join('\n') + '\n');
console.log(`${wanted.size} files, ${faces.length} @font-face rules -> ds/tokens/fonts.css`);
